version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mariadb
            - redis
        environment:
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
    mariadb:
        image: mariadb:10.4.32
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ROOT_PASSWORD: root_password
        volumes:
            - mariadb_data:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: '1'
            PMA_HOST: mariadb
volumes:
    mysql_data:
    mariadb_data:
